# Enable the Kyria OLED Display
CONFIG_ZMK_DISPLAY=y

# Boost bt power to 11 (well, 8)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Slow down the debouncing to 20ms, as the Kyria is a bit noisy
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=20
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=20